[2018-07-05 15:01:16,105] ERROR {com.zaxxer.hikari.pool.HikariPool} - HikariPool-1 - Exception during pool initialization. 
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.ballerinalang.database.sql.SQLDatasource.buildDataSource(SQLDatasource.java:200)
	at org.ballerinalang.database.sql.SQLDatasource.init(SQLDatasource.java:65)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createSQLDataSource(SQLDatasourceUtils.java:1211)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createServerBasedDBClient(SQLDatasourceUtils.java:1140)
	at org.ballerinalang.database.mysql.CreateClient.execute(CreateClient.java:59)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:386)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:257)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:407)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:148)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:80)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:317)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:264)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:244)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:464)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:473)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunctions(BLangFunctions.java:123)
	at org.ballerinalang.BLangProgramRunner.runService(BLangProgramRunner.java:53)
	at org.ballerinalang.launcher.LauncherUtils.runServices(LauncherUtils.java:144)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:114)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
 
[2018-07-05 15:02:10,343] ERROR {com.zaxxer.hikari.pool.HikariPool} - HikariPool-1 - Exception during pool initialization. 
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.ballerinalang.database.sql.SQLDatasource.buildDataSource(SQLDatasource.java:200)
	at org.ballerinalang.database.sql.SQLDatasource.init(SQLDatasource.java:65)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createSQLDataSource(SQLDatasourceUtils.java:1211)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createServerBasedDBClient(SQLDatasourceUtils.java:1140)
	at org.ballerinalang.database.mysql.CreateClient.execute(CreateClient.java:59)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:386)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:257)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:407)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:148)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:80)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:317)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:264)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:244)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:464)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:473)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunctions(BLangFunctions.java:123)
	at org.ballerinalang.BLangProgramRunner.runService(BLangProgramRunner.java:53)
	at org.ballerinalang.launcher.LauncherUtils.runServices(LauncherUtils.java:144)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:114)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
 
[2018-07-06 11:24:08,304] ERROR {com.zaxxer.hikari.pool.HikariPool} - HikariPool-1 - Exception during pool initialization. 
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.ballerinalang.database.sql.SQLDatasource.buildDataSource(SQLDatasource.java:200)
	at org.ballerinalang.database.sql.SQLDatasource.init(SQLDatasource.java:65)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createSQLDataSource(SQLDatasourceUtils.java:1211)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createServerBasedDBClient(SQLDatasourceUtils.java:1140)
	at org.ballerinalang.database.mysql.CreateClient.execute(CreateClient.java:59)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:386)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:257)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:407)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:148)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:80)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:317)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:264)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:244)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:464)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:473)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunctions(BLangFunctions.java:123)
	at org.ballerinalang.BLangProgramRunner.runService(BLangProgramRunner.java:53)
	at org.ballerinalang.launcher.LauncherUtils.runServices(LauncherUtils.java:144)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:114)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
 
[2018-07-06 17:12:46,420] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-06 20:51:06,062] ERROR {org.ballerinalang.net.http.BallerinaHTTPConnectorListener} - Error in HTTP server connector: Remote client closed connection before initiating outbound response  
[2018-07-07 13:46:36,232] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 13:49:10,468] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:19:59,873] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:26:50,510] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:49:20,225] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:50:09,350] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:52:22,726] ERROR {org.ballerinalang.net.http.HttpConnectorPortBindingListener} - Error in http endpoint 
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
 
[2018-07-07 17:52:48,715] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:53:14,085] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:54:03,182] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:54:34,140] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 17:57:37,912] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 19:12:47,564] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 19:19:49,030] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-07 20:20:09,601] ERROR {org.ballerinalang.net.http.HttpUtil} - call failed  
[2018-07-08 16:10:30,723] ERROR {com.zaxxer.hikari.pool.HikariPool} - HikariPool-1 - Exception during pool initialization. 
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.ballerinalang.database.sql.SQLDatasource.buildDataSource(SQLDatasource.java:200)
	at org.ballerinalang.database.sql.SQLDatasource.init(SQLDatasource.java:65)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createSQLDataSource(SQLDatasourceUtils.java:1211)
	at org.ballerinalang.database.sql.SQLDatasourceUtils.createServerBasedDBClient(SQLDatasourceUtils.java:1140)
	at org.ballerinalang.database.mysql.CreateClient.execute(CreateClient.java:59)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.util.program.BLangFunctions.invokeNativeCallable(BLangFunctions.java:386)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:257)
	at org.ballerinalang.bre.bvm.CPU.tryExec(CPU.java:407)
	at org.ballerinalang.bre.bvm.CPU.exec(CPU.java:148)
	at org.ballerinalang.bre.bvm.BLangScheduler.executeNow(BLangScheduler.java:80)
	at org.ballerinalang.util.program.BLangFunctions.invokeNonNativeCallable(BLangFunctions.java:317)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:264)
	at org.ballerinalang.util.program.BLangFunctions.invokeCallable(BLangFunctions.java:244)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:464)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunction(BLangFunctions.java:473)
	at org.ballerinalang.util.program.BLangFunctions.invokePackageInitFunctions(BLangFunctions.java:123)
	at org.ballerinalang.BLangProgramRunner.runService(BLangProgramRunner.java:53)
	at org.ballerinalang.launcher.LauncherUtils.runServices(LauncherUtils.java:144)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:114)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:256)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:66)
 
